In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.size

6

In [7]:
arr.shape

(6,)

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr1=np.array([1,2,3,4,5,6], dtype='int32')

In [10]:
arr1.dtype

dtype('int32')

In [11]:
arr1.ndim

1

In [12]:
b = np.arange(1,9,3)

In [13]:
print(b)

[1 4 7]


In [14]:
x=np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [15]:
x1 = np.array(x.reshape(5,4))
print(x1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [16]:
x2 = x[8:14]
print(x2)

[ 9 10 11 12 13 14]


In [17]:
x1[0,:]

array([1, 2, 3, 4])

In [18]:
x1[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
x1[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [20]:
x1[1:4:2,0:4:3]

array([[ 5,  8],
       [13, 16]])

In [21]:
x1[:,2]

array([ 3,  7, 11, 15, 19])

In [22]:
x1[:,2:3]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [23]:
a = np.arrange(1,25)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
a = np.arange(1,25)

In [ ]:
a1=a.reshape(2,3,4)

In [ ]:
a1[0:2,:,:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
a1[0:1,:,:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
a1[:,0:1,:]

array([[[ 1,  2,  3,  4]],

       [[13, 14, 15, 16]]])

In [38]:
ax = np.arange(0,9)

In [25]:
ax

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
ax[-5:-7:-1] = [71,81]

In [40]:
ax

array([ 0,  1,  2, 81, 71,  5,  6,  7,  8])

In [ ]:
print(np.random.randint(100))  #random int from 0 to 100

41


In [62]:
print(np.random.rand(10))  #random float number of 10

[0.23698688 0.10476575 0.48419249 0.3917378  0.53221145 0.62508963
 0.49483647 0.64511304 0.84460484 0.28655477]


In [ ]:
print(np.random.randint(100 , size = 5))  #random 5 number from 0 to 100

[93 23 80  2 70]


In [ ]:
print(np.random.randint(100 , size = (5,4)))  #random 5*4 array from 0 to 100

[[24 31  5 75]
 [70 44 37 46]
 [63 69 69 45]
 [38 27  3  2]
 [76  5  9 59]]


In [63]:
print(np.random.rand(3,5))  #random float array3*5 between 0 to 100

[[0.65383394 0.81731461 0.82392706 0.81283573 0.21602135]
 [0.37081791 0.12766143 0.14971643 0.89656367 0.30219948]
 [0.44856573 0.12540006 0.34570691 0.84405116 0.85670696]]
